development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: isitintheeruv_dev
  pool: 25
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: isitintheeruv_test
  pool: 25
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: isitintheeruv_prod
  pool: 25
  username: root
  password:
